## **Steo-by-step calculation**:

In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import eig

In [2]:
A = np.array([[1,2,3,4],[5,5,6,7],[1,4,2,3],[5,3,2,1],[8,1,2,2]]) #5 data points with 4 features
A

array([[1, 2, 3, 4],
       [5, 5, 6, 7],
       [1, 4, 2, 3],
       [5, 3, 2, 1],
       [8, 1, 2, 2]])

In [3]:
df = pd.DataFrame(A,columns = ['f1', 'f2', 'f3','f4'])
df

   f1  f2  f3  f4
0   1   2   3   4
1   5   5   6   7
2   1   4   2   3
3   5   3   2   1
4   8   1   2   2

In [4]:
#Standardize the data points
df_std = df-df.mean()
df_std

    f1   f2   f3   f4
0 -3.0 -1.0  0.0  0.6
1  1.0  2.0  3.0  3.6
2 -3.0  1.0 -1.0 -0.4
3  1.0  0.0 -1.0 -2.4
4  4.0 -2.0 -1.0 -1.4

In [5]:
#calculate the covariance
df_cov = np.cov(df_std.T)
df_cov

array([[ 9.  , -1.5 ,  0.25, -1.25],
       [-1.5 ,  2.5 ,  1.75,  2.25],
       [ 0.25,  1.75,  3.  ,  3.75],
       [-1.25,  2.25,  3.75,  5.3 ]])

In [6]:
#eigenvalue decomposition
eig_values, eig_vectors = eig(df_cov)

In [7]:
#eigenvectors
eig_vectors

array([[ 0.69478464, -0.69892736, -0.12618005, -0.11337302],
       [-0.34820806, -0.17035429, -0.15768352, -0.9082216 ],
       [-0.32341225, -0.47997101,  0.81222066,  0.07300647],
       [-0.53984254, -0.50210337, -0.54727699,  0.39616934]])

In [8]:
#eigenvalues
eig_values

array([10.6066305 +0.j,  7.90808697+0.j,  0.09465667+0.j,  1.19062586+0.j])

In [9]:
#Choose the first 2 eigenvectors
eig_2d = eig_vectors[:,:2]
eig_2d

array([[ 0.69478464, -0.69892736],
       [-0.34820806, -0.17035429],
       [-0.32341225, -0.47997101],
       [-0.53984254, -0.50210337]])

In [10]:
self_calculated = np.dot(df_std,eig_2d)
self_calculated

array([[-2.06005139,  1.96587434],
       [-2.91530135, -4.2871211 ],
       [-1.89321273,  2.60724014],
       [ 2.31381898,  0.98609174],
       [ 4.55474649, -1.27208513]])

In [11]:
# We can also directly import PCA function from sklearn to 
from sklearn.decomposition import PCA
pca = PCA(2)
reduced_data = pca.fit_transform(A)

In [12]:
# Compare self-calculated result and result calculated by sklearn
print("Step-by-step calculated\n", self_calculated)
print("Sklearn calculated\n", reduced_data)

Step-by-step calculated
 [[-2.06005139  1.96587434]
 [-2.91530135 -4.2871211 ]
 [-1.89321273  2.60724014]
 [ 2.31381898  0.98609174]
 [ 4.55474649 -1.27208513]]
Sklearn calculated
 [[-2.06005139 -1.96587434]
 [-2.91530135  4.2871211 ]
 [-1.89321273 -2.60724014]
 [ 2.31381898 -0.98609174]
 [ 4.55474649  1.27208513]]

## **All in one**:

In [14]:
import numpy as np
from scipy.linalg import eig


def question4_sol(data):
    M = np.mean(data.T, axis=1)
    C = A - M
    V = np.cov(C.T)
    eig_values, eig_vectors = eig(df_cov)
    result = np.dot(C,np.round(eig_vectors[:,:2],4))
    return np.around(result, 4)


A = np.array([[1,2,3,4],[5,5,6,7],[1,4,2,3],[5,3,2,1],[8,1,2,2]]) #5 data points with 4 features

question4_sol(A)

array([[-2.0601,  1.9658],
       [-2.9151, -4.2873],
       [-1.8933,  2.6071],
       [ 2.3137,  0.9861],
       [ 4.5547, -1.2719]])